---
applications:
- name: initializr-api
  path: ../../src/InitializrApi/bin/Debug/netcoreapp3.1/publish
  buildpacks:
    - https://github.com/cloudfoundry/dotnet-core-buildpack.git#v2.3.14
  memory: 1024M
  env:
    ASPNETCORE_ENVIRONMENT: Development
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
